### ISSUE TITLE
Need for Speed : Hot Pursuit 3D (2013 Bonus Edition) - Black Screen

### ISSUE THREAD

**Issue by reenaosm** [nikita36078/J2ME-Loader#649] opened 2020-03-26 00:54 UTC
**Emulator version:**v.1.5.6

**Game version:**v.4.16.3

**Game resolution:**240x320

**Device:**Android v4.4.4 BIHEE A9

**Android version:**v4.4.4

**Description of the issue:**
Like Need for Speed : Hot Pursuit 3D, this game also has a black screen problem.

Here are the screenshots from that game:
![Screenshot_20200325-235048](https://user-images.githubusercontent.com/62536531/77599104-a8de0700-6f3e-11ea-8285-cbbc0113f4dd.png)
![Screenshot_20200325-235055](https://user-images.githubusercontent.com/62536531/77599105-aa0f3400-6f3e-11ea-899e-66d5805d39da.png)
![Screenshot_20200325-235100](https://user-images.githubusercontent.com/62536531/77599107-aaa7ca80-6f3e-11ea-9946-607fe36528d8.png)
![Screenshot_20200325-235031](https://user-images.githubusercontent.com/62536531/77599108-aaa7ca80-6f3e-11ea-8d89-47305a2e5055.png)
![Screenshot_20200325-235038](https://user-images.githubusercontent.com/62536531/77599109-ab406100-6f3e-11ea-848e-56edc1b23c9d.png)

I wonder if this is also launched by Mascot Capsule engine, and whether this problem can be fixed or not.

Thanks~~ (^_^)

**Comment by amarcioz** [comment] 2020-03-26 23:16
This game was released for Sony Ericsson.  Most 3D games for Sony Ericsson use Mascot Capsule.  Try this version but it is not in English:
[NeedForSpeedHotPursuit-Czech_Nokia2700_N95.zip](https://github.com/nikita36078/J2ME-Loader/files/4390499/NeedForSpeedHotPursuit-Czech_Nokia2700_N95.zip)

**Comment by nikita36078** [comment] 2020-03-27 18:41
Duplicate of #434. As I've said before, the Mascot Capsule support is in the development.

**Closed by nikita36078** 2020-03-27 18:41 UTC

**Comment by amarcioz** [comment] 2020-03-27 21:26
> Duplicate of #434. As I've said before, the Mascot Capsule support is in the development.

This is good news.
