### ISSUE TITLE
An error occurred during installation and the game cannot be run

### ISSUE THREAD

**Issue by xiexin52k** [nikita36078/J2ME-Loader#814] opened 2021-08-01 04:38 UTC
**Emulator version: 1.7.0-open**

**Game version: 1.0.0**

**Game resolution:  240x320**

**Device: Xiaomi Redmi Note3(6.0) , Xiaomi Redmi Note9 Pro(11.0)**

**Description of the issue:**
During the game installation process, there will be an error: 
```java.lang.ArrayIndexOutOfBoundsException: length=3; index=21```

Debug breakpoint:
![debug](https://user-images.githubusercontent.com/19523795/127759285-38f89d10-1e4c-458e-a6e9-81ff10be5ce0.png)

the labels array length is 3, but offset is 21.
I tried the Override method, Expand the array, this will cause an error when converting dex later.

this game jar file( replace .zip to .jar)
[机械狂潮.zip](https://github.com/nikita36078/J2ME-Loader/files/6912134/default.zip)

**Comment by woesss** [comment] 2021-08-05 07:14
Both problems are caused by incorrect bytecode.  
Perhaps this is an unsuccessful modification of the application or protection against reverse engineering using the specific features of the virtual machine of a certain line of devices.  
This can only be fixed by manually editing the bytecode.

**Comment by xiexin52k** [comment] 2021-08-05 07:20
Oh~, this is really a bad notice, because I found that many games have this problem (╥﹏╥)

**Comment by woesss** [comment] 2021-08-05 08:07
The problem from the screenshot can be circumvented by using the SKIP_FRAMES option.  
[`AndroidProducer.java:57`](https://github.com/nikita36078/J2ME-Loader/blob/2455ed30c55c248c0c57c9a77742975249b53fcf/app/src/main/java/org/microemu/android/asm/AndroidProducer.java#L57):  

```
cr.accept(cv, ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
```  

Others, as I said, only by editing the bytecode

**Comment by xiexin52k** [comment] 2021-08-05 08:11
> The problem from the screenshot can be circumvented by using the SKIP_FRAMES option.
> [`AndroidProducer.java:57`](https://github.com/nikita36078/J2ME-Loader/blob/2455ed30c55c248c0c57c9a77742975249b53fcf/app/src/main/java/org/microemu/android/asm/AndroidProducer.java#L57):
> 
> ```
> cr.accept(cv, ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
> ```
> 
> Others, as I said, only by editing the bytecode

Thanks. I'll try as you say

**Comment by xiexin52k** [comment] 2021-08-05 11:08
It seems that we can't handle this error. This flag just skips the ClassReader error, but can't skip the dex convert error.
One of them will always make an error in this case. 

I'll close this issues.

**Closed** 2021-08-05 11:09 UTC
