### ISSUE TITLE
Add Volume Booster

### ISSUE THREAD

**Issue by MCPE-Beta1177** [nikita36078/J2ME-Loader#564] opened 2019-09-17 18:38 UTC
Yes, You read the title right! i'm using speaker boost because i can't hear the midi files, it's too quiet to hear it while playing java games on j2me loader

**Comment by MCPE-Beta1177** [comment] 2019-09-18 11:16
Also why you haven't answered me! Add Volume Booster to this emulator so i can hear the midi files

**Comment by nikita36078** [comment] 2019-09-20 20:06
Any examples of games with the quiet sound? Did you try to increase multimedia volume? Usually it's very loud at high volume levels.

**Comment by MCPE-Beta1177** [comment] 2019-09-21 10:59
@nikita36078 Yeah, Some Of These Java Games are having an issue with a quiet sound because i'm using speaker boost

**Comment by MCPE-Beta1177** [comment] 2019-09-21 11:03
@nikita36078 thanks, but i'm closing this issue because you read the title right

**Comment by MCPE-Beta1177** [comment] 2019-09-23 00:19
@nikita36078 Yeah, some of these java games are having an issue with a quiet sound! I tried to increase multimedia volume, but Speaker Boost Doesn't Allow me To play Java Games at high boost! Maybe You Should Develop App Called Volume Booster For J2ME Loader! Now that i closed this issue, i can now reopen it! Forgive me for this

**Comment by woesss** [comment] 2019-09-23 11:41
The emulator directs sounds from java games to a multimedia stream, like any music player or game for Android. Accordingly, the emulator does not require special conditions. It is not clear what your problem is. Give examples of problematic games, also can record a video demonstrating the problem.

**Comment by MCPE-Beta1177** [comment] 2019-09-26 03:01
@woesss the emulator does support Speaker Boost On Hawaii Phones! I hope it supports Samsung using Speaker Boost and then play Java Games at high boost

**Comment by MCPE-Beta1177** [comment] 2019-09-27 22:30
> The emulator directs sounds from java games to a multimedia stream, like any music player or game for Android. Accordingly, the emulator does not require special conditions. It is not clear what your problem is. Give examples of problematic games, also can record a video demonstrating the problem.

Same Here, i'm also using Speaker Boost To Boost My Multimedia Volume, but it can't direct sounds on J2ME Loader because i'm having issues with it

**Comment by MCPE-Beta1177** [comment] 2019-10-03 04:50
@nikita36078 i hope you add volume booster

**Comment by MCPE-Beta1177** [comment] 2019-10-19 12:53
nitkita, if you could solve the low volume problem, i will give you 5 stars in google play store

**Comment by nikita36078** [comment] 2019-10-24 20:02
So you don't hear sounds at all? It's not a low volume problem then.

**Comment by MCPE-Beta1177** [comment] 2019-10-25 03:43
@nikita36078 i wish there was something that supports speaker boost in J2ME Loader

**Comment by nikita36078** [comment] 2019-10-25 06:26
There's already the "Limit FPS" option in the game settings. By default the frames count is unlimited.

**Comment by MCPE-Beta1177** [comment] 2019-10-25 17:33
@nikita36078 thanks for letting me know, but will you add Speaker Boost Support For J2ME Loader! I know it's a duplicate, but people wanted a speaker boost support for J2ME Loader

**Comment by woesss** [comment] 2019-10-26 09:09
You use this: https://play.google.com/store/apps/details?id=mobi.omegacentauri.SpeakerBoost ? I tried it and it works with the J2ME-Loader same as with other applications. The problem is in the Booster itself or your device does not use sound effects for MIDI.

**Comment by MCPE-Beta1177** [comment] 2019-10-26 11:14
@woesss you're right! my booster does not allow sound and music effects for midi! I guess J2ME Loader does not support speaker boost because i installed the modded version from a different website called a2zapk.com

**Comment by MCPE-Beta1177** [comment] 2019-10-27 20:07
@nikita36078 please add sis or sisx support for j2me loader

**Comment by nikita36078** [comment] 2019-11-25 18:13
Seems like the problem is missing sound in some games, then it's the same issue as #571

**Comment by nikita36078** [comment] 2019-12-02 08:11
I will close this issue and leave another one opened.

**Closed by nikita36078** 2019-12-02 08:11 UTC

**Comment by MCPE-Beta1177** [comment] 2019-12-04 05:21
@nikita36078 thank you for closing this issue, but when the 1.5.6 will be released on google play store
