### ISSUE TITLE
3D Robot Alliance

### ISSUE THREAD

**Issue by uforgivent** [nikita36078/J2ME-Loader#478] opened 2019-03-20 14:09 UTC
**Emulator version:** 1.4.2

**Game version:** 2.0

**Game resolution:** 240x320

**Device:** Samsung Galaxy J6

**Android version:** 8.0

**Description of the issue:** Some textures in the game aren't loaded...
![Screenshot_20190320-105931_J2ME Loader](https://user-images.githubusercontent.com/5973208/54690603-87af3300-4b00-11e9-8b57-ff4b6b384c20.jpg)

**Comment by woesss** [comment] 2019-03-20 14:22
Duplicate of #240

In this game, Mascot Capsule 3D API is used. But J2ME Loader does not support it.

**Comment by nikita36078** [comment] 2023-07-09 17:57
Fixed

**Closed by nikita36078** 2023-07-09 17:57 UTC
Labels: bug, mascot capsule
