### ISSUE TITLE
Feature request: Custom soundfont

### ISSUE THREAD

**Issue by lucmsilva651** [nikita36078/J2ME-Loader#1007] opened 2023-07-24 22:01 UTC
### Quick summary

**A option on the settings menu to change the default Android soundfont to a custom one for emulation.**

### Details

**My feature request is: Implement a feature in the settings menu or in the game properties menu which you can select the default soundfont for the game emulation.**

_An Hipotetical Example: "I have Asphalt 6 installed and I prefer to use a custom soundfont because it sounds better."_
In the options menu (or the game properties, but it's other case and method suggestion) you can add a option for choosing my default soundfont. But in the options menu case, the custom soundfont implements in all games installed on the emulator.

**In the custom game properties menu to implement custom soundfonts, each game has your soundfont.** _I can choose the default soundfont of Android or choose my custom soundfont for playing the game._
_Example: Game A -> Soundfont A | Game B -> Soundfont B | Game C -> Default soundfont_

**I hope you guys will add one of this features (or both), it's very requested for the people I know.
And sorry for a bad typo, English isn't my main language and I don't prefer the use of translators.**

**Comment by kreb0sh** [comment] 2023-07-24 22:11
+1

**Comment by woesss** [comment] 2023-07-25 03:35
Duplicate of #569

**Closed** 2023-08-12 17:33 UTC
Labels: enhancement
