### ISSUE TITLE
Working Directory 

### ISSUE THREAD

**Issue by VisionR1** [nikita36078/J2ME-Loader#1047] opened 2024-02-28 20:19 UTC
### Quick summary

Add newer APIs for allow us to grant access through DocumentsUI, to be able to choose our path 

### Details

Android 11 MIUI 12.5, with latest J2ME (Google play) i click the working Directory and does nothing

**Comment by woesss** [comment] 2024-02-29 08:11
Duplicate of #928

**Comment by VisionR1** [comment] 2024-02-29 08:46
> Duplicate of #928

Yeah i know, but no one responded with new, from 2022, for that i add the lab enhancement

**Comment by woesss** [comment] 2024-02-29 09:27
I don't think duplicating requests will speed up progress. You can remind and vote by commenting or reacting. If this is critical for you and you can't wait any longer, you can use [JL-Mod](https://github.com/woesss/JL-Mod), where external storage support is provided through permission for file managers.

**Closed** 2024-02-29 11:54 UTC
Labels: enhancement

**Comment by woesss** [comment] 2024-02-29 15:50
> i dont understand why the programer of J2ME, at first not include this
Due to Google Play restrictions

**Comment by VisionR1** [comment] 2024-02-29 16:09
> > i dont understand why the programer of J2ME, at first not include this
> 
> Due to Google Play restrictions

Yeah, i read about this and i think now with the new grant access through DocumentsUI can (like you add in your mod), or in this version not Google Play
