### ISSUE TITLE
treasure towers

### ISSUE THREAD

**Issue by Geanpiere** [nikita36078/J2ME-Loader#702] opened 2020-06-05 17:56 UTC
![Screenshot_20200115-124304](https://user-images.githubusercontent.com/66488715/83909429-63a03780-a72e-11ea-991b-2f89f96e90ff.png)
![Screenshot_20200115-124304]

**Emulator version:1.6.1

**Game version:1.4.4

**Game resolution:240x320

**Device:**
MOTOROLA

**Android version:7.0.0

**Description of the issue:the game treasure towers by giving new game the game screen; while; the character's airship should appear with the castle.

**Comment by stevenfelix505** [comment] 2020-06-06 00:42
Duplicate of #349 

Use this emulator mod to play that game:
https://github.com/woesss/JL-Mod/releases

**Closed** 2020-06-06 20:34 UTC

**Comment by Geanpiere** [comment] 2020-07-20 03:06
while; A new version of the original emulator has already been released in
the play store, which made them fix the sound problems, apart from the mod
J2ME emulator does not answer the left, right and top touch buttons in the
treasure towers only fix that error please would be greatly appreciated.
