### ISSUE TITLE
Prince of Persia - Bug: The game is very fast.

### ISSUE THREAD

**Issue by amarcioz** [nikita36078/J2ME-Loader#389] opened 2018-10-12 02:23 UTC
Emulator version: 1.3.6

Game version: 1.0.5

Game resolution:640x360

Device: Samsung Galaxy J1 2016

Android version: 5.1

Description of the issue: 
The game is very fast. This also happens with other games. Could not implement an option in the settings to decrease or increase the speed of the games?
![screenshot_2018-10-11-23-13-22](https://user-images.githubusercontent.com/35005836/46844285-b33d2d00-cdac-11e8-98b4-89fe66ad44dc.png)

**Comment by 1234Sameer** [comment] 2018-10-12 03:30
Duplicate of #378
So, comment on that issue.

**Closed** 2018-10-15 19:04 UTC
