### ISSUE TITLE
I hope your emulator can support sd card emulate

### ISSUE THREAD

**Issue by mini536** [nikita36078/J2ME-Loader#443] opened 2019-01-23 02:42 UTC
**Emulator version:**

1.4.0
**Game version:**

0.7
**Game resolution:**
``(For example, 240x320 or 640x360)``
240×320
**Device:**
``(For example, Samsung Galaxy S7)``
xiaomi 1
**Android version:**
4.1.2
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
when i run it,it says:
Загрузка...
Вставьте карту памяти!

**Comment by woesss** [comment] 2019-01-23 06:19
Duplicate of #321

**Closed** 2019-01-23 11:06 UTC

**Comment by AdityaMH** [comment] 2019-02-15 10:48
Not sd card but external memory card.
